server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: business-microservice01-product
          uri: lb://business-microservice01-product
          predicates:
            - Path=/api/products/**
        - id: business-microservice02-client
          uri: lb://business-microservice02-client
          predicates:
            - Path=/api/products/**